### Create student POST request
POST http://localhost:8080/student
Content-Type: application/json

{
  "name": "Bob Denard",
  "age": 22,
  "facultyId": 2
}

### Create faculty POST request
POST http://localhost:8080/faculty
Content-Type: application/json

{
  "name": "Witchery",
  "color": "blue"
}

### GET all students
GET http://localhost:8080/student
Accept: application/json

### GET all students count
GET http://localhost:8080/student/all-students-count
Accept: application/json

### GET average age of all students
GET http://localhost:8080/student/avg-students-age
Accept: application/json

### GET five students that were added last
GET http://localhost:8080/student/five-last-students
Accept: application/json

### GET avatars (using pagination)
GET http://localhost:8080/avatar?page=1&size=3
Accept: application/json

### GET a student by ID
GET http://localhost:8080/student/1
Accept: application/json

### Send a form with the text and file fields
PATCH http://localhost:8080/student/2/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="harry.jpg"
Content-Type: image/jpeg

< harry.jpg
--WebAppBoundary