### Create student POST request
POST http://localhost:8080/student
Content-Type: application/json

{
  "name": "Silvio Berlusconni",
  "age": 26,
  "facultyId": 2
}

### Create faculty POST request
POST http://localhost:8080/faculty
Content-Type: application/json

{
  "name": "Witchery",
  "color": "blue"
}

### GET all students
GET http://localhost:8080/student
Accept: application/json

### GET all students count
GET http://localhost:8080/student/allStudentsCount
Accept: application/json

### GET average age of all students
GET http://localhost:8080/student/avgStudentsAge
Accept: application/json

### GET students that were added last
GET http://localhost:8080/student/lastStudents?count=2
Accept: application/json

### GET avatars (using pagination)
GET http://localhost:8080/avatar
Accept: application/json

### GET a student by ID
GET http://localhost:8080/student/60
Accept: application/json

### GET a faculty by ID
GET http://localhost:8080/faculty/70
Accept: application/json

### Send a form with the text and file fields
PATCH http://localhost:8080/student/11/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="idol.jpg"
Content-Type: image/jpeg

< idol.jpg
--WebAppBoundary